#!/usr/bin/env sh
#copyright john morris beck 2026 gpl2
a="/tmp/.fastlang";
b=",PROT_READ|PROT_WRITE,MAP_SHARED,";
if [ ! -d "$a" ] ; then
mkdir $a;
printf '%s' "
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <stdint.h>
#include <sys/mman.h>
#define c(x,y) case x:y;break;
#define a r[p['g'][p['t']+1]]
#define b r[p['g'][p['t']+2]]
char s[2000];
int i,**p[256],r[256],main(int argc,char **argv){
    p['g']=(int*)(intptr_t)open(*argv,O_RDWR);
    ftruncate((int)(intptr_t)p['g'], 9999);
    p['g']=(int*)mmap(0,9999$b(int)(intptr_t)p['g'],0);
  p['t']=p['g'];
  while(42!=*(p['t']++)=getchar());
  p['t']=p['g'];
  while(1){
    switch(*p['t']){
    c('b',a=p['t'][2])
      c('-',a-=b)
      c('<',a=a<b)
      c('m',p['g'][a]=p['g'][b])
      c('\"',for(i=0;i<b;s[i]=p['g'][p['t'][1]+i]))
      c('O',p[a]=(int*)(intptr_t)open(s,O_RDWR))
      c('t',ftruncate((int)(intptr_t)p[a],b))
      c('a',p[a]=(int*)mmap(0,p[b][0]$b(int)(intptr_t)p[b+1],0))
      c('f',munmap(p[a],b))
      c('c',memcpy(p[p['g'][a]],p[p['g'][a+1]],p['g'][a+2]))
      c('p',p[a]=p[b])
      c('i',a=getchar())
      c('o',putchar(p['g'][a]))
      c('x',p['t']=p['g']+a-3)
    default:
      exit(0);}
    p['t']+=3;}}//copyright john morris beck 2026 gpl2
">"$a/macrosh.c";
filcc "$a/macrosh.c" -o "$a/macrosh.exe";
printf '%s' '
#!/usr/bin/env sh
a='"$a"';
b="$$$1";
awk  '\''
$1=="elfc"{d["open"]=$3"=open("$4",O_RDWR)";
d["ftruncate"]=$1"("$2","$3")";
d["map"]=$3"=mmap(0,"$4"'"$b"'"$5",0)";
d["munmap"]=$2"("$3","$4")";
d["memcpy"]=$2"("$3","$4","$5")";
d["var"]=$3" "$4;d["ctrl"]=$3"("$4"){";
d["key"]="case "$3":";p=$3"=";for(i=3;
i<=NF&&$2=="op";i++){p=p" "$i}d["op"]=p;
d["get"]=$3"=*("$4"*)("$5")";
d["set"]="*("$3"*)("$4")="$5;
d["seek"]=$3"=(void*)((char*)"$3"+(intptr_t)"$4")"}
{print $1=="elfc"?d[$3]:$0}#copyright 2026 john morris beck gpl2
'\'' - >$a/$b.c;
trap '\''rm -f "$a/$b.exe"'\'' EXIT;
filcc "$a/$b.c" -o $a/$b.exe;
rm "$a/$b.c";
chmod +x "$a/$b.exe"
$a/$b.exe& #copyright 2026 john morris beck gpl2
'>"$a/elfc.sh";
printf '%s' '
#!/usr/bin/sh
{
printf "%s" '\''
i=0;
elfc(){
i="$((i + 1))";
/tmp/.fastlang/elfc.sh "$i";
};
'\'';
/tmp/.fastlang/macrosh.exe;
} | sh; #copyright 2026 john morris beck
'>"$a/fastlang.sh";
chmod +x "$a/macrosh.exe" "$a/elfc.sh" "$a/fastlang.sh";
fi;
fastlang(){ "$a/fastlang.sh";};
