#!/usr/bin/env sh
#copyright john morris beck 2026 gpl2
cat << 'EOF' > /tmp/.macrosh
#include <stdlib.h>
#include <stdio.h>
#define c(x,y) case x:y;break;
#define a r[p['g'][p['t']+1]]
#define b r[p['g'][p['t']+2]]
int *p[256],r[256],main(){


//incomplete block 1
    p['g']=open($4,O_RDWR))
    ftruncate(p['g'],$3))
    p['g']=mmap(0,$4,PROT_READ|PROT_WRITE,MAP_SHARED,$5,0))

  while(42!=*--t=getchar());
  t++;
  while(1){
    switch(*t){
    c('b',a=*t+2)
      c('-',a-=b)
      c('<',a=a<b)
      c('m',p['g'][a]=p['g'][b])

//incomplete block 2
      c('o',p[a]=open($4,O_RDWR))
      c('t',ftruncate(m,$3))
      c('a',p[a]=mmap(0,$4,PROT_READ|PROT_WRITE,MAP_SHARED,$5,0))
      c('f',munmap(p[a],$4);
      c('c',memcpy(p[a],p[b],$5)
      c('g',m=p['a'])

      C('i',a=getchar())
      c('x',t=m+a-3)
    default:
      exit(0);}
    t+=3;}}//copyright john morris beck 2026 gpl2
EOF
macrosh() { tcc -run "/tmp/.macrosh" | sh -c '
elfc(){
cat | ( awk '\''
$1=="elfc"{
d["open"]=$3"=open("$4",O_RDWR)";
d["prep"]="ftruncate("$2","$3")";
d["map"]=$3"=mmap(0,"$4",PROT_READ|PROT_WRITE,MAP_SHARED,"$5",0)";
d["munmap"]=$2"("$3","$4")";
d["memcpy"]=$2"("$3","$4","$5")";
d["var"]=$3" "$4;d["ctrl"]=$3"("$4"){";
d["key"]="case "$3":";p=$3"=";for(i=3;
i<=NF&&$2=="op";i++){p=p" "$i}d["op"]=p;
d["get"]=$3"=*("$4"*)("$5")";
d["set"]="*("$3"*)("$4")="$5;
d["seek"]=$3"=(void*)((char*)"$3"+(intptr_t)"$4")";
}
{
print $1=="elfc"?d[$3]:$0
} 
'\'' > /tmp/.elfc$$.c;
trap rm "/tmp/.elfc$$.c" ;
tcc -run "/tmp/.elfc$$.c";
) &
} ; #copyright john morris beck 2026 gpl2
' ; } ;

